import Head from "next/head";

export default function Home() {
  return (
      <div>
        <Head>
          <title>FUDO PIZZA</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <h1>hossein kouhzad frontend developer</h1>        
        </main>
      </div>
  );
}

